#' @title National Flood Hazard Layer Metadata
#' @description A data.frame specifying Layer ID for each date type.
#' @export

nfhl_meta = data.frame(type = c('NFHL Availability',
'LOMRs',
'LOMAs',
'FIRM Panels',
'Base Index',
'PLSS',
'Topographic Low Confidence Areas',
'River Mile Markers',
'Datum Conversion Points',
'Coastal Gages',
'Gages', 
'Nodes', 
'High Water Marks', 
'Station Start Points', 
'Cross-Sections', 
'Coastal Transects',
'Base Flood Elevations',
'Profile Baselines',
'Transect Baselines',
'Limit of Moderate Wave Action', 
'Water Lines',
'Political Jurisdictions',
'Levees',
'General Structures', 
'Primary Frontal Dunes', 
'Hydrologic Reaches', 
'Flood Hazard Boundaries', 
'Flood Hazard Zones', 
'Submittal Information', 
'Alluvial Fans', 
'Subbasins',
'Water Areas'),

layerID = c(0:32)[-22])
